python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 256, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.5, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 256, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 512, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 24, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 512, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 512, "d_score": 64, "dropout": 0, "e_layers": 1, "head_dropout": 0, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 256, "d_score": 64, "dropout": 0.2, "e_layers": 1, "head_dropout": 0, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 2048, "d_model": 1024, "d_score": 64, "dropout": 0, "e_layers": 2, "head_dropout": 0.2, "horizon": 336, "k": 1, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 24, "patience": 5, "scaling": 0.75, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 512, "d_score": 64, "dropout": 0.1, "e_layers": 1, "head_dropout": 0, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 256, "d_score": 32, "dropout": 0.3, "e_layers": 2, "head_dropout": 0.1, "horizon": 96, "k": 1, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.5, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 64, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 96, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 2, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 64, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 192, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 2, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 512, "d_model": 256, "d_score": 256, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.25, "score_threshold": 0.5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 512, "dropout": 0.1, "e_layers": 2, "head_dropout": 0, "horizon": 720, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 256, "d_score": 32, "dropout": 0.2, "e_layers": 2, "head_dropout": 0.4, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 1024, "d_model": 512, "d_score": 128, "dropout": 0.2, "e_layers": 2, "head_dropout": 0, "horizon": 192, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 512, "d_score": 256, "dropout": 0.2, "e_layers": 3, "head_dropout": 0.2, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 1024, "d_model": 256, "d_score": 128, "dropout": 0.3, "e_layers": 2, "head_dropout": 0, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 512, "d_model": 256, "d_score": 64, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.25, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 512, "d_model": 512, "d_score": 512, "dropout": 0, "e_layers": 2, "head_dropout": 0, "horizon": 192, "k": 1, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.75, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 512, "d_model": 256, "d_score": 64, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0.1, "e_layers": 2, "head_dropout": 0, "horizon": 720, "k": 1, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 0.75, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0.1, "e_layers": 2, "head_dropout": 0, "horizon": 96, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 24, "patience": 5, "scaling": 0.5, "score_threshold": 0.2, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 64, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 192, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 8, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0.1, "e_layers": 4, "head_dropout": 0, "horizon": 336, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0, "e_layers": 4, "head_dropout": 0, "horizon": 720, "k": 1, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0.2, "e_layers": 2, "head_dropout": 0.2, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 2, "patch_len": 16, "patience": 5, "scaling": 0.75, "score_threshold": 0, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 1024, "d_model": 128, "d_score": 256, "dropout": 0.2, "e_layers": 2, "head_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 16, "patience": 5, "scaling": 0.75, "score_threshold": 0, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 32, "d_ff": 1024, "d_model": 512, "d_score": 256, "dropout": 0.2, "e_layers": 2, "head_dropout": 0.2, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 3, "patch_len": 16, "patience": 5, "scaling": 0.5, "score_threshold": 0, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SEER"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "seer_modify_copy.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 1024, "d_model": 512, "d_score": 512, "dropout": 0.4, "e_layers": 2, "head_dropout": 0.2, "horizon": 720, "k": 1, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 8, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 24, "patience": 5, "scaling": 1, "score_threshold": 0, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SEER"

